using RXM.API;
using RXM.Configuration;
using RXM.Devices.ST2;
using RXM.Serial;
using RXM.SXM;
using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace RXM
{
    class Program
    {
        public static int Index = 0;

        private static CancellationTokenSource? Rotat;
        private static CancellationTokenSource? ChannelToken;
        private static CancellationTokenSource? Delay;
        public static readonly SemaphoreSlim ChannelLock = new(1, 1);
        private static readonly AppConfig Config = Configuration.Configuration.Config;
        private static PresetManager PresetManager = null!;
        private static SerialConnection SM = null!;
        private static Devices.ST2.SXM Sirius = null!;

        public static async Task Main()
        {
            // loads channels generated by xmgen.py
            ChannelInfo.LoadJSON(Config.Paths.ChannelJson);
            if (!ChannelInfo.Channels.Any())
            {
                Console.WriteLine("Couldn't get any channels from loaded json");
                return;
            }

            // main serial connection
            SM = new SerialConnection(Config.Serial.Port, Config.Serial.BaudRate);
            SM.Open();

            // add this because it takes a bit to load sometimes not sure why
            Console.WriteLine("Loading... (may take a while)");

            // sirius stuff
            var Presets = Config.Paths.PresetsJson;
            Devices.ST2.PresetManager.EnsurePresetsJson(Presets);
            if (!File.Exists(Presets))
            {
                Console.WriteLine("Sirius (Presets) Could not load presets json!");
            }
            PresetManager = new PresetManager(Presets);
            Sirius = new Devices.ST2.SXM(SM, 1, PresetManager, Tune: async (i) => await StartChannel(i, null!));
            SM.DataReceived += (_, packet) =>
            {
                // stupid way to do this
                Favourites.Saved(packet, Sirius.CurrentUUID);
            };

            // start httplistener (REQUIRES ADMINISTRATOR TO LISTEN ON 0.0.0.0)
            var server = new RNETApi(SM);
            server.Start();

            var display = new Display(SM);
            VLC.Init();

            Sirius.SetDisplay(display);

            var iBridge = new RXM.Devices.SMS3.SMS3(SM, source: 3);
            try
            {
                await iBridge.StartAsync(StartNP: true);
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Couldn't start iBrige {ex.Message}");
            }

            var rnet = new RnetDetector(SM);

            rnet.ButtonPressed += async (_, e) =>
            {
                if (e.SourceName == "SiriusXM")
                {
                    HandleXM(e.EventId, display, e.Zone, e.Packet);
                }
                else if (e.SourceName == "Roon")
                {
                    await HandleRoon(e.EventId, display);
                }
                else if (e.SourceName == "iPod")
                {
                    iBridge.HandlePress(e);
                }
                else
                {
                    Console.WriteLine("Bad source");
                }
            };

            _ = StartChannel(Index, display);

            await Roon.Roon.Load();
            Roon.Roon.StartRotation(display);

            Console.WriteLine("Loaded, Press enter to stop");
            Console.ReadLine();

            Sirius.Stop();
            VLC.Stop();
        }

        private static async Task ShowChannel(int index, Display display, CancellationToken token)
        {
            if (index < 0 || index >= ChannelInfo.Channels.Count)
                return;

            Index = index;

            if (token.IsCancellationRequested)
                return;

            var channel = ChannelInfo.Channels[index];
            VLC.Play(channel.Url, Config.VLC.Volume);

            Sirius.OnChannelShown(index);
        }

        public static async Task StartChannel(int index, Display? display)
        {
            if (index < 0 || index >= ChannelInfo.Channels.Count)
                return;

            Index = index;

            var channel = ChannelInfo.Channels[Index];
            SM.SendChannelandCat(1, channel.Name, "N/A");

            Delay?.Cancel();
            Delay = new CancellationTokenSource();
            var token = Delay.Token;

            try
            {
                await Task.Delay(3000, token);

                if (token.IsCancellationRequested)
                    return;

                await ChannelLock.WaitAsync();
                try
                {
                    ChannelToken?.Cancel();
                    Rotat?.Cancel();
                    ChannelToken = new CancellationTokenSource();
                }
                finally
                {
                    ChannelLock.Release();
                }

                if (display != null)
                    _ = ShowChannel(Index, display, ChannelToken.Token);
                else
                    _ = ShowChannel(Index, Sirius.Display!, ChannelToken.Token);
            }
            catch (TaskCanceledException)
            {
            }
        }

        // roon events
        private static async Task HandleRoon(byte eventId, Display display)
        {
            switch (eventId)
            {
                case 0x2F: RXM.Roon.Roon.PlayNext(display); break;
                case 0x30: RXM.Roon.Roon.PlayPrevious(display); break;
                case 0x1A: RXM.Roon.Roon.Play(display); break;
                case 0x1E: RXM.Roon.Roon.Pause(display); break;
                case 0x1B: RXM.Roon.Roon.Pause(display); break;
            }

            await Task.CompletedTask;
        }


        // sirius events
        private static void HandleXM(int eventId, Display display, byte zone, byte[]? packet)
        {
            if (eventId == 0x27)
            {
                Sirius.Refresh();
                return;
            }

            // usually sends 0x01 when changing pages, so if were in preset mode and we get that then that indicates that the user has changed pages
            if (eventId == 0x01 && Sirius.InPresetMode)
            {
                Sirius.ExitPresetMode();
                return;
            }

            // presets page
            if (eventId == 0x06)
            {
                if (!Sirius.InPresetMode)
                    Sirius.EnterPresetMode();
                else
                    Sirius.SendBank();

                return;
            }

            if (Sirius.InPresetMode)
            {
                switch (eventId)
                {
                    case 0x0E:
                        Sirius.Mem(+1);
                        break;

                    case 0x0F:
                        Sirius.Mem(-1);
                        break;

                    default:
                        HandlePresetMode(eventId, display);
                        return;
                }
            }

            switch (eventId)
            {
                case 0x2F:
                    Index = (Index + 1) % ChannelInfo.Channels.Count;
                    _ = StartChannel(Index, display);
                    break;

                case 0x30:
                    Index = (Index - 1 + ChannelInfo.Channels.Count) % ChannelInfo.Channels.Count;
                    _ = StartChannel(Index, display);
                    break;

                case 0x1A:
                    VLC.Play(ChannelInfo.Channels[Index].Url);
                    break;

                case 0x1E:
                case 0x1B:
                    VLC.Pause();
                    break;
                     
                // i dont think these NEED to be in the main handler but it works so, dont know any other buttons that use these
                case 0x75: Sirius.PlayPreset(1); break;
                case 0x76: Sirius.PlayPreset(2); break;
                case 0x77: Sirius.PlayPreset(3); break;
                case 0x78: Sirius.PlayPreset(4); break;
                case 0x79: Sirius.PlayPreset(5); break;
                case 0x7A: Sirius.PlayPreset(6); break;

                case 0x2A: Sirius.EnterPresetMode(); break;
                case 0x29: Sirius.EnterPresetMode(); break;

                case 0x6F:
                    _ = Sirius.HandleFavourite(zone, 0x6F);
                    break;

                case 0x70:
                    _ = Sirius.HandleFavourite(zone, 0x70);
                    break;
            }
        }

        private static void HandlePresetMode(int eventId, Display display)
        {
            switch (eventId)
            {
                case 0x2A:
                    Sirius.PrevBank();
                    break;

                case 0x29:
                    Sirius.NextBank();
                    break;

                // stupid
                case 0x75: Sirius.PlayPreset(1); break;
                case 0x76: Sirius.PlayPreset(2); break;
                case 0x77: Sirius.PlayPreset(3); break;
                case 0x78: Sirius.PlayPreset(4); break;
                case 0x79: Sirius.PlayPreset(5); break;
                case 0x7A: Sirius.PlayPreset(6); break;

                case 0x3C: Sirius.SavePreset(1); break;
                case 0x3D: Sirius.SavePreset(2); break;
                case 0x3E: Sirius.SavePreset(3); break;
                case 0x3F: Sirius.SavePreset(4); break;
                case 0x40: Sirius.SavePreset(5); break;
                case 0x41: Sirius.SavePreset(6); break;

                case 0x1A:
                case 0x1B:
                case 0x1E:
                    Sirius.ExitPresetMode();
                    break;

                case 0x2F:
                case 0x30:
                    Sirius.ExitPresetMode();
                    HandleXM(eventId, display, 0, null);
                    break;
            }
        }
    }
}
